
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amal Sunil
 */
public class Employee_details2 extends javax.swing.JFrame {

    /**
     * Creates new form Employee_details2
     */
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";   //specifying the driver name
    static final String DB_URL = "jdbc:mysql://localhost/student";  //specifying database url
    
    //Database credentials
    static final String USER = "root";
    static final String PASSWORD = "";
    public Employee_details2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 240, 240));

        jLabel1.setText("Employee details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Location"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Show data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton1)
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();
            String sql;
            
//            st.executeUpdate("insert into employee values (4,'Mbappe',22,'Paris'),(6,'Di Maria',29,'Paris')");
            sql="Select * from stud";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
            //Extract data from the result set
            while(rs.next())
            {
                //Retrieving by column name 
//                int id=rs.getInt("id");
//                String name=rs.getString("name");
//                String loc=rs.getString("location");
                int id=rs.getInt(1);
                String name=rs.getString(2);
                String loc=rs.getString(3);
                
                //Display the extracted data
                System.out.print("ID: "+id+"    Name :"+name+"   Location: "+loc+"\n");
                String[] x={String.valueOf(id),name,loc}; //creating  an array of strings to insert it into the table(GUI frame)
                m.addRow(x); //adding the row to the table(GUI frame)
            }
            rs.close();
            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }

                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                Connection conn=null;
        Statement st=null;
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();
            String sql;
            String xx = JOptionPane.showInputDialog(null, "Enter the ID : ");//prompt window to enter the id being searched
            int n = Integer.valueOf(xx);
//            st.executeUpdate("insert into employee values (4,'Mbappe',22,'Paris'),(6,'Di Maria',29,'Paris')");
            sql="Select * from stud where id="+n;
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
            //Extract data from the result set
            while(rs.next())
            {
                //Retrieving by column name 
//                int id=rs.getInt("id");
//                String name=rs.getString("name");
//                String loc=rs.getString("location");
                int id=rs.getInt(1);
                String name=rs.getString(2);
                String loc=rs.getString(3);
                
                //Display the extracted data
                System.out.print("ID: "+id+"    Name :"+name+"   Location: "+loc+"\n");
                String[] x={String.valueOf(id),name,loc}; //creating  an array of strings to insert it into the table(GUI frame)
                m.addRow(x); //adding the row to the table(GUI frame)
            }
            rs.close();
            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }

   
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_details2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_details2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_details2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_details2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_details2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
