

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;  

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amal Sunil
 */
public class ResultSetFunctions extends javax.swing.JFrame {

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";   //specifying the driver name
    static final String DB_URL = "jdbc:mysql://localhost/football_db";  //specifying database url
    
    //Database credentials
    static final String USER = "root";
    static final String PASSWORD = "";    
    /**
     * Creates new form ResultSetFunctions
     */

    public ResultSetFunctions() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ResultSetFunctions");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "AGE", "LOCATION"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("NAME");

        jLabel4.setText("AGE");

        jLabel5.setText("LOCATION");

        jButton1.setText("SHOW DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("INSERT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();
            String sql;
            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
//            st.executeUpdate("insert into employee values (4,'Mbappe',22,'Paris'),(6,'Di Maria',29,'Paris')");


            sql="Select * from player";
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next())
            {
                //Retrieving by column name 
                int id=rs.getInt("id");
                String name=rs.getString("name");
                int age=rs.getInt("age");
                String loc=rs.getString("location");
                
                //Display the extracted data
                System.out.print("ID: "+id+"    Name :"+name+"    Age :"+age+"   Location: "+loc+"\n");
                        
                
                String[] x={String.valueOf(id),name,String.valueOf(age),loc}; //creating  an array of strings to insert it into the table(GUI frame)
                m.addRow(x); //adding the row to the table(GUI frame)
            }
            rs.close();
            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();
            String sql;

//            st.executeUpdate("insert into employee values (4,'Mbappe',22,'Paris'),(6,'Di Maria',29,'Paris')");
            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
            
            String xx = JOptionPane.showInputDialog(null, "Enter the ID of the player to be searched : ");//prompt window to enter the id being searched(default value, i.e if no input is given it takes null as the value)
            int n = Integer.valueOf(xx);
            sql="Select * from player where id="+n;
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next())
            {
                //Retrieving by column name 
                int id=rs.getInt("id");
                String name=rs.getString("name");
                int age=rs.getInt("age");
                String loc=rs.getString("location");
                
                //Display the extracted data
                System.out.print("ID: "+id+"    Name :"+name+"    Age :"+age+"   Location: "+loc+"\n");
                        
                
                String[] x={String.valueOf(id),name,String.valueOf(age),loc}; //creating  an array of strings to insert it into the table(GUI frame)
                m.addRow(x); //adding the row to the table(GUI frame)
            }   

            rs.close();
            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }
         
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();
            String sql;

//            st.executeUpdate("insert into employee values (4,'Mbappe',22,'Paris'),(6,'Di Maria',29,'Paris')");
            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
            

            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }
         
         
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        JFrame frame=new JFrame();  
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);

            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();
            String sql="select id from player";
            
            ResultSet rs=st.executeQuery(sql);
            rs.last();
            
            int id=rs.getInt("id")+1;
            String name = JOptionPane.showInputDialog(null, "Enter the name : ");//prompt window to enter the id being searched(default value, i.e if no input is given it takes null as the value)
            String age = JOptionPane.showInputDialog(null, "Enter the age : ");//prompt window to enter the id being searched(default value, i.e if no input is given it takes null as the value)
            String location = JOptionPane.showInputDialog(null, "Enter the location : ");//prompt window to enter the id being searched(default value, i.e if no input is given it takes null as the value)
            
            jLabel6.setText("Last inserted record : ");
            jTextField1.setText(String.valueOf(id));            
            jTextField2.setText(name);            
            jTextField3.setText(age);            
            jTextField4.setText(location);       


            sql="insert into player VALUES ("+id+",'"+name+"',"+age+",'"+location+"')";
//            System.out.println(sql);
            st.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(frame, "Insertion successful");
            
            rs.close();
            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        JFrame frame=new JFrame();  
        try
        {
            //Registering the driver(translator)
            Class.forName(JDBC_DRIVER);
            
            //Open a connection(like a road)
            System.out.println("Connecting to database");
            conn=DriverManager.getConnection(DB_URL,USER,PASSWORD);

            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();//creating an object of jTable1 to control it
            m.setRowCount(0);//emptying all the rows displayed in there.
            
            //Execute a query(statement object carries the sql query and the database engine queries/processes it and sends the response as a resultset object)
            System.out.println("Creating statement");
            st=conn.createStatement();

            
            
            String id = JOptionPane.showInputDialog(null, "Enter ID of the player to be deleted : ");//prompt window to enter the id being searched(default value, i.e if no input is given it takes null as the value)
            String sql="select * from player where id="+id;
            
            ResultSet rs=st.executeQuery(sql);
            rs.next();
            
            jLabel6.setText("Last deleted record : ");
            jTextField1.setText(id);            
            jTextField2.setText(rs.getString("name"));            
            jTextField3.setText(String.valueOf(rs.getInt("age")));            
            jTextField4.setText(rs.getString("location"));       


            sql="delete from player where id="+id;
//            System.out.println(sql);
            st.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(frame, "Deletion  successful");
            
            rs.close();
            conn.close();
            st.close();
        }
        catch(SQLException se)
        {
            //Handle error for jdbc
            se.printStackTrace();
        }
        catch(Exception e)
        {
            //Handle error for Class.forName
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultSetFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultSetFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultSetFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultSetFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultSetFunctions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
